name = "CitableParserBuilder"
uuid = "c834cb9d-35b9-419a-8ff8-ecaeea9e2a2a"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.2.0"

[deps]
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CitableObject = "0.3"
julia = "1.5"
