name = "CitableParserBuilder"
uuid = "c834cb9d-35b9-419a-8ff8-ecaeea9e2a2a"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"

[compat]
CitableObject = "0.2"