# Analyses and citable texts


A [morphological analysis](./analyses.qmd) represents the results of analyzing a string value morphologically.

When we are analyzing citable texts, however, we are not simply working with arbitrary strings. First, as [this discussion](./analyses.qmd) notes, since a morphological parser operates on lexical tokens, that implies that analyzing a text as a series of classified tokens according to a specified orthographic system precedes morphological anlaysis. Second, the resulting tokens have a context in the citable text. We want to associate the string values we will parse morphologically with this citable context

A morphological analysis produces a list (in Julia, a `Vector`) of analysis objects, so with each citable token, we want to associate a list of analysis objects.  If the list is empty, that means that no analyis was found for the given token. If the list has more than one analysis, that means the individual token is morphologically ambiguous.


A concrete example may clarify this.  Here's a brief illustration.

