project:
  type: website
jupyter: julia-1.10  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "Package version: `0.27.2`"
format:
  html: 
    toc: true


website:
  title: "Citable morphological parsers"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Concepts"
        file: concepts/index.qmd          
      - text: "Tutorials"
        file: tutorials/index.qmd  
      
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  

    right:   
      - icon: github
        href: https://github.com/neelsmith/CitableParserBuilder.jl
        aria-label: GitHub
      - icon: person-circle
        menu:
          - text: "About me"
            href: https://neelsmith.quarto.pub
          - text: "More of my digital scholarship"
            href: https://neelsmith.quarto.pub/digschol/
        aria-label: "More of my work"  

  
  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd
        - text: "---"
        - tutorials/parsers.qmd
        - tutorials/parsing.qmd
        - tutorials/parsecitable.qmd
        - tutorials/corpus.qmd
        - tutorials/serialization.qmd
        - tutorials/generating.qmd


    - title: "Guides"
      contents:
        - guides/index.qmd
        - guides/abbrurns.qmd
        - guides/tokenvectors.qmd
        - guides/buildone.qmd
        - guides/parserbackends.qmd

    - title: "Reference"
      contents: 
        - reference/index.qmd
        - reference/apis.qmd
        - text: "---"
        - reference/gburg.qmd
        - reference/sfst.qmd

    - title: "Concepts"
      contents: 
        - concepts/index.qmd
        - concepts/analyses.qmd        
        - concepts/architecture.qmd
        - concepts/analysis-implementation.qmd        

        

    - title: "Home"
      contents:
        - index.qmd               
 

